### ISSUE TITLE
TileLerp Tool

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/kcg-image-tools#1]
In Folder TileLerp

Take two images in from command line
- images must be same size
- images must have RGBA (4 channels)
- should also be able to call from python as a function library
- return a linear interpolation of the two images
- takes in a parameter from 0.0 to 1.0 for interpolation amount
- outputs single image to disc (one option)
- outputs 16x16 grid with different a factors (see below)

1> Takes in image as pixel array (4 bytes per pixel, width, height of image, int array for pixels, etc)

2> Make a linear interpolation function

Called Lerp. For each pixel:

a is 0 to 1

a*x + (1-a)*y
- a is lerp factor
- x is pixel in first image
- y is pixel in second image
 
Takes two images in training set and linear interpolation parameter a, and creates a new image by combination

3> Command line test, to show 16x16 image grid

- start image is x

- end image is y

- then stepwise linear interpolations between them from 0 to 255

---

Also
- option to enforce tile-size, default to 64 (64x64)
- error if tile size does not match parameter if set

**Comment by Volpe95** [comment]
@haltingstate Please review and let me know if I am missing something, also I didn't get what you mean with the last notes in the issue. 
> Also
> option to enforce tile-size, default to 64 (64x64)
> error if tile size does not match parameter if set

If you could give me more explanations and examples

Thanks.
